### ISSUE TITLE
changing FOV Doesn't change zooms fov

### ISSUE THREAD

**Issue by CreatorNic** [LogicalGeekBoy/logical_zoom#1]
when you're at the default fov at 70 it zooms perfectly. but when you scale it to fov 30 it doesn't scale the zoom to a longer zoom. 

otherwise working perfectly
great job btw
- CreatorNic

**Comment by LogicalGeekBoy** [comment]
Hi @CreatorNic, thanks for taking the time to report this issue. At the moment this is actually working as intended. I'll probably add an option to configure the zoom level as it's currently fixed. This should make it better for players that play on different FoV settings.

Thanks again <3
