### ISSUE TITLE
Make zooming possible only when certain item is in the inventory.

### ISSUE THREAD

**Issue by RDKRACZ** [LogicalGeekBoy/logical_zoom#11]
Add optional check to make zooming work only when a configurable (enter ID) item is present in the inventory.
Firstly I wanted something like a spyglass but realized I can do the item by myself.

**Comment by 0xJoeMama** [comment]
Hmm this would normally require something like cloth config and adding it to this mod wouldn't really make sense. However I will look into parsing the item manually.

**Comment by LogicalGeekBoy** [comment]
I'm not planning on adding an item requirement, thanks for the suggestion though!
