### ISSUE TITLE
Make zoom stack with spyglass like optifine's

### ISSUE THREAD

**Issue by JarheadHME** [LogicalGeekBoy/logical_zoom#15]
I've been seeing in videos of people using optifine that their zoom will stack onto the spyglass, but when using logical zoom it instead overrides the spyglass's zoom, I'd like if this could be made to stack as well :)

**Comment by Cythorg** [comment]
I've made a pull request that implements this feature. Hopefully it is merged :)

**Comment by JarheadHME** [comment]
#16
