### ISSUE TITLE
Consider releasing on Modrinth.

### ISSUE THREAD

**Issue by sebihotza** [LogicalGeekBoy/logical_zoom#22]
[Modrinth](https://modrinth.com) is a new and open source platform to release mods. Please consider releasing your mods on Modrinth.
Note: I'm not affiliated with Modrinth, I'm just a user.

**Comment by BD103** [comment]
I would also greatly appreciate if this mod were released on Modrinth. It has a nicer interface and is being integrated with the Fabric community more and more.

**Comment by LogicalGeekBoy** [comment]
Thanks for the suggestion, I've added it now and you can get it here: https://modrinth.com/mod/logical-zoom
