### ISSUE TITLE
zoom does not work underwater

### ISSUE THREAD

**Issue by ChloeIsNobody** [LogicalGeekBoy/logical_zoom#24]
whenever I try to activate the zoom underwater, nothing happens. Also, when I have the key held above water and go under, the zoom is deactivated, but the cinematic camera stays active until I resurface, even if I let go of the key.

**Comment by LogicalGeekBoy** [comment]
I've tested this and it works just fine for me. Do you have any other mods installed that might be causing an issue?

**Comment by ChloeIsNobody** [comment]
I apologize, I just tested the mod Ok Zoomer and experienced the same issue, so it's almost definitely a different mod causing the issue. So sorry!
