### ISSUE TITLE
Redraws after exiting zoom

### ISSUE THREAD

**Issue by andrei1015** [LogicalGeekBoy/logical_zoom#3]
Noticed an issue after releasing the zoom button, the chunks that were outside of the viewport while zoomed in perform what looks like a redraw. Does not seem to happen every time.

https://www.youtube.com/watch?v=JWWxyW7cYT4

**Comment by LogicalGeekBoy** [comment]
I've seen this issue too. It seems to only happen in your mouse isn't moving when you release the zoom key. If the camera is moving when you release it seems to be fine. I'll need to do some investigation on how to fix it.

**Comment by PeterGamesGR** [comment]
Not easy to fix. We need to delve deep in the rendering engine, since minecraft is coded to stop drawing chunks that are out of view. There is probably a very small bug, that doesnt make the rendering engine update when fov changes. May be fixed in 1.17 since they are adding the telescope.

**Comment by andrei1015** [comment]
oh yea for sure
