### ISSUE TITLE
Upload version 1.19 to Modrinth

### ISSUE THREAD

**Issue by guineuu** [LogicalGeekBoy/logical_zoom#30]
The latest version In Modrinth is still the 1.18.2 one.

**Comment by intergrav** [comment]
Yes, please do this

**Comment by drwoops** [comment]
indeed. keep releases on modrinth up to date.

**Comment by intergrav** [comment]
I've already switched to zoomify but I would gladly switch back to logical zoom if it was updates were maintained on there

**Comment by LogicalGeekBoy** [comment]
The build for 1.19.1 is now on Modrinth. There was a bug which prevented the 1.19 version being published. It's here: https://modrinth.com/mod/logical-zoom
