### ISSUE TITLE
Version 0.0.19 for 1.19.4 detected as Wacatac.B!ml trojan by Windows Defender

### ISSUE THREAD

**Issue by Evtema3** [LogicalGeekBoy/logical_zoom#44]
When I download the latest 0.0.19 release of this mod for 1.19.4 on either CurseForge or Modrinth, it gets flagged as a trojan by Windows Defender (Windows 11 Version 22H2). For the time being, I  have deleted the download out of precaution.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/63302963/225712169-6426a165-9826-4e11-b099-9db9c420319c.png">

**Comment by LogicalGeekBoy** [comment]
I've just downloaded the jar (just in case) and scanned it with my Windows Defender and it comes up clean for me.

**Comment by Evtema3** [comment]
Hmm, alright. Well at the moment every time I download it (even after restarting) it gets flagged as a virus and auto-removed from my machine. Hopefully it's just a bug with Windows Defender that'll resolve itself sooner or later.

**Comment by Evtema3** [comment]
I just tried downloading it again from Modrinth and it worked without issue. Sorry for the false alarm!
