### ISSUE TITLE
Modrinth Featured Versions Outdated

### ISSUE THREAD

**Issue by MrZeroSkill** [LogicalGeekBoy/logical_zoom#59]
https://modrinth.com/mod/logical-zoom/versions#all-versions Hello! Was just browsing Modrinth and noticed that the featured versions are all for 1.19, while the 1.20 and 1.21 releases are all out. Just wanted to point this out in case it was a mistake.

**Comment by LogicalGeekBoy** [comment]
Thanks, all fixed :)
