### ISSUE TITLE
CurseForge "unmaintained" message

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [LogicalGeekBoy/logical_zoom#6]
CurseForge has slapped the following warning message on [your project](https://www.curseforge.com/minecraft/mc-mods/logical-zoom):

> This project is abandoned and its default file will likely not work with the most recent version of Minecraft. Whether this project is out of date or its author has marked it as abandoned, this project is no longer maintained.

Is this actually true? You just updated the project a few months ago, and it looks fine…

**Comment by PeterGamesGR** [comment]
Pretty sure this was fixed since there was a 1.16.5 jar uploaded.
Curseforge marks projects as abondoned if no files are uploaded for a while.

**Comment by JamesTheAwesomeDude** [comment]
Yep, it's gone now!
