### ISSUE TITLE
[Feature request] Increase/decrease the zoom level with a mouse wheel.

### ISSUE THREAD

**Issue by RDKRACZ** [LogicalGeekBoy/logical_zoom#9]
Other zoom mods have this functionality.

**Comment by 0xJoeMama** [comment]
Try getting my repo. I have added that functionality, without using the scroll wheel.

**Comment by LogicalGeekBoy** [comment]
This mod is designed to be super simple, I'm not planning on adding zoom levels. Thanks though.
